improve script "comp" in a better way.
In struct 'case', the rest option can be '*) cmd ;;'.

Signed-off-by: alex <1603361791@qq.com>

diff --git a/Shell/comp b/Shell/comp
--- a/Shell/comp
+++ b/Shell/comp
@@ -2,27 +2,39 @@
 
 # The script can compile files of different languages in an easy way.
 
-test "$1" != "" || exit 1
+cmd="${0##*/}"	# In case of modifying the name of file.
+
+# Usage
+usage()
+{
+	cat <<-EOF >&2
+	Usage: $cmd <file>
+	[Only support '.c' '.cpp' files]
+	EOF
+}
 
 # C.
 comp_c()
 {
 	x=${1%%.c*}		# '%%' %%O* --> 截取最后"O"的左侧str，删除右侧str
-	echo ${x}		# '%' --> 截取最前"O"的左侧str。
-	gcc -g -o ${x} $1
+					# '%' --> 截取最前"O"的左侧str。
+	gcc -g -o ${x} $1 && echo ${x}
 }
 
 # C++.
 comp_c_plus()
-{	
+{
 	x=${1%%.cpp*}
-	echo ${x}
-	g++ $1 -o ${x}
+	g++ $1 -o ${x} && echo ${x}
 }
 
-case ${1##*.} in		# '##' ##*O --> 截取最后"."的右侧str，保留左侧str
+test -z $1 && usage
+
+
+case ${1##*.} in		# '##' ##*O --> 截取最后"."的右侧str，删除左侧str
 	"c") comp_c $1 ;;
 	"cpp") comp_c_plus $1 ;;
+	*) echo "Cannot Compile the file!" ;;
 esac
 
 exit 1
